import 'package:fluxer_app/features/input/domain/keybind_action.dart';
import 'package:fluxer_app/features/input/domain/keybind_section.dart';
import 'package:fluxer_app/l10n/generated/fluxer_localizations.dart';

String keybindActionLabel(FluxerLocalizations l10n, KeybindAction action) {
  switch (action) {
    case KeybindAction.systemToggleShortcutsOverlay:
      return l10n.keybindActionShowShortcutsList;
    case KeybindAction.messageEdit:
      return l10n.chatMessageEdit;
    case KeybindAction.messageDelete:
      return l10n.chatMessageDelete;
    case KeybindAction.messagePin:
      return l10n.chatMessagePin;
    case KeybindAction.messageReact:
      return l10n.chatMessageAddReaction;
    case KeybindAction.messageReply:
      return l10n.chatMessageReply;
    case KeybindAction.messageForward:
      return l10n.chatMessageForward;
    case KeybindAction.messageSpeak:
      return l10n.chatMessageSpeak;
    case KeybindAction.messageCopyText:
      return l10n.keybindActionCopyText;
    case KeybindAction.messageMarkUnread:
      return l10n.keybindActionMarkUnread;
    case KeybindAction.messageFocusTextarea:
      return l10n.keybindActionFocusTextarea;
    case KeybindAction.navGuildPrev:
    case KeybindAction.navGuildNext:
      return l10n.keybindActionSwitchCommunities;
    case KeybindAction.navChannelPrev:
    case KeybindAction.navChannelNext:
      return l10n.keybindActionSwitchChannels;
    case KeybindAction.navHistoryBack:
      return l10n.keybindActionHistoryBack;
    case KeybindAction.navHistoryForward:
      return l10n.keybindActionHistoryForward;
    case KeybindAction.navUnreadPrev:
    case KeybindAction.navUnreadNext:
      return l10n.keybindActionJumpUnreadChannels;
    case KeybindAction.navMentionPrev:
    case KeybindAction.navMentionNext:
      return l10n.keybindActionJumpMentionChannels;
    case KeybindAction.navCurrentCall:
      return l10n.keybindActionJumpCurrentCall;
    case KeybindAction.navToggleLastGuildDms:
      return l10n.keybindActionToggleLastGuildDms;
    case KeybindAction.navGuildTabPrev:
      return l10n.keybindActionPreviousCommunityOrDms;
    case KeybindAction.navGuildTabNext:
      return l10n.keybindActionNextCommunityOrDms;
    case KeybindAction.navGuildSlot1:
      return l10n.keybindActionGoToDms;
    case KeybindAction.navGuildSlot2:
      return l10n.keybindActionGoToFirstCommunity;
    case KeybindAction.navGuildSlot3:
      return l10n.keybindActionGoToSecondCommunity;
    case KeybindAction.navGuildSlot4:
      return l10n.keybindActionGoToThirdCommunity;
    case KeybindAction.navGuildSlot5:
      return l10n.keybindActionGoToFourthCommunity;
    case KeybindAction.navGuildSlot6:
      return l10n.keybindActionGoToFifthCommunity;
    case KeybindAction.navGuildSlot7:
      return l10n.keybindActionGoToSixthCommunity;
    case KeybindAction.navGuildSlot8:
      return l10n.keybindActionGoToSeventhCommunity;
    case KeybindAction.navGuildSlot9:
      return l10n.keybindActionGoToEighthCommunity;
    case KeybindAction.navQuickSwitcher:
      return l10n.keybindActionToggleQuickSwitcher;
    case KeybindAction.navAddGuild:
      return l10n.keybindActionCreateOrJoinCommunity;
    case KeybindAction.dndStart:
      return l10n.keybindActionStartDragAndDrop;
    case KeybindAction.dndMoveUp:
    case KeybindAction.dndMoveDown:
      return l10n.keybindActionMove;
    case KeybindAction.dndDrop:
      return l10n.keybindActionDropItem;
    case KeybindAction.dndCancel:
      return l10n.keybindActionCancel;
    case KeybindAction.chatMarkGuildRead:
      return l10n.keybindActionMarkCommunityRead;
    case KeybindAction.chatMarkChannelRead:
      return l10n.keybindActionMarkChannelRead;
    case KeybindAction.chatNewDm:
      return l10n.keybindActionStartGroupDm;
    case KeybindAction.chatTogglePins:
      return l10n.keybindActionTogglePinnedMessages;
    case KeybindAction.chatToggleInbox:
      return l10n.keybindActionToggleInbox;
    case KeybindAction.chatMarkInboxRead:
      return l10n.keybindActionMarkTopInboxRead;
    case KeybindAction.chatMarkAllInboxRead:
      return l10n.keybindActionMarkAllInboxRead;
    case KeybindAction.chatToggleMemberList:
      return l10n.keybindActionToggleMemberList;
    case KeybindAction.chatToggleEmoji:
      return l10n.keybindActionToggleEmojiPicker;
    case KeybindAction.chatToggleGif:
      return l10n.keybindActionToggleGifPicker;
    case KeybindAction.chatToggleSticker:
      return l10n.keybindActionToggleStickerPicker;
    case KeybindAction.chatScrollUp:
      return l10n.keybindActionScrollChatUp;
    case KeybindAction.chatScrollDown:
      return l10n.keybindActionScrollChatDown;
    case KeybindAction.chatJumpOldestUnread:
      return l10n.keybindActionJumpOldestUnread;
    case KeybindAction.chatFocusTextarea:
      return l10n.keybindActionFocusComposer;
    case KeybindAction.chatUpload:
      return l10n.keybindActionUploadFile;
    case KeybindAction.chatCopyChannelLink:
      return l10n.keybindActionCopyChannelLink;
    case KeybindAction.chatToggleSavedMedia:
      return l10n.keybindActionToggleSavedMedia;
    case KeybindAction.chatSendVoiceMessage:
      return l10n.keybindActionSendVoiceMessage;
    case KeybindAction.voiceToggleMute:
      return l10n.voiceControlMute;
    case KeybindAction.voiceToggleDeafen:
      return l10n.voiceControlDeafen;
    case KeybindAction.voiceAnswerCall:
      return l10n.keybindActionAnswerCall;
    case KeybindAction.voiceDeclineCall:
      return l10n.keybindActionDeclineCall;
    case KeybindAction.voiceStartDmCall:
      return l10n.keybindActionStartDmCall;
    case KeybindAction.voiceToggleSoundboard:
      return l10n.keybindActionToggleSoundboard;
    case KeybindAction.voiceToggleCompactCallView:
      return l10n.keybindActionToggleCompactCallView;
    case KeybindAction.voicePushToTalkPriority:
      return l10n.keybindActionPushToTalkPriority;
    case KeybindAction.voicePriorityVad:
      return l10n.keybindActionVoiceActivityPriority;
    case KeybindAction.miscHelp:
      return l10n.keybindActionOpenHelp;
    case KeybindAction.miscSearch:
      return l10n.keybindActionSearchMessages;
    case KeybindAction.miscOpenContextMenu:
      return l10n.keybindActionOpenContextMenu;
    case KeybindAction.systemToggleSettings:
      return l10n.keybindActionOpenSettings;
    case KeybindAction.systemOpenThemeStudioPopout:
      return l10n.keybindActionOpenThemeStudio;
    case KeybindAction.systemZoomIn:
      return l10n.keybindActionZoomIn;
    case KeybindAction.systemZoomOut:
      return l10n.keybindActionZoomOut;
    case KeybindAction.systemZoomReset:
      return l10n.keybindActionZoomReset;
  }
}

String keybindSectionLabel(FluxerLocalizations l10n, KeybindSection section) {
  switch (section) {
    case KeybindSection.defaults:
      return l10n.keybindSectionDefaults;
    case KeybindSection.messages:
      return l10n.keybindSectionMessages;
    case KeybindSection.navigation:
      return l10n.keybindSectionNavigation;
    case KeybindSection.dragAndDrop:
      return l10n.keybindSectionDragAndDrop;
    case KeybindSection.chat:
      return l10n.keybindSectionChat;
    case KeybindSection.voiceAndVideo:
      return l10n.keybindSectionVoiceAndVideo;
    case KeybindSection.misc:
      return l10n.keybindSectionMisc;
  }
}
