enum UserSettingsSection {
  profile,
  securityLogin,
  // fluxerPlutonium,
  // giftsAndCodes,
  privacyDashboard,
  authorizedApps,
  blockedUsers,
  linkedDevices,
  connections,
  lookAndFeel,
  accessibility,
  chat,
  audioAndVideo,
  keybinds,
  notifications,
  languageAndTime,
  advanced,
  applications,
  developerTools,
  limitsConfig,
  featureFlags,
  whatsNew,
}
